# Generated by Django 4.2.7 on 2023-12-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP_ENTITY_NAME', models.CharField(max_length=200)),
                ('SP_ENTITY_ID', models.CharField(max_length=200)),
                ('SP_EXCHANGE_TICKER', models.CharField(max_length=200)),
                ('IQ_INDUSTRY_CLASSIFICATION', models.CharField(max_length=200)),
                ('IQ_SECTOR', models.CharField(max_length=200)),
                ('IQ_INDUSTRY_GROUP', models.CharField(max_length=200)),
                ('IQ_INDUSTRY', models.CharField(max_length=200)),
                ('IQ_PRIMARY_INDUSTRY', models.CharField(max_length=200)),
                ('SP_GEOGRAPHY', models.CharField(max_length=200)),
                ('SP_COUNTRY_NAME', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('financials', models.TextField()),
                ('recent_news', models.TextField()),
            ],
        ),
    ]
